name: tax_code_flutter
description: "App for Italian Tax Code calculation."
publish_to: none # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  animated_reorderable_list: ^1.1.1
  build_runner: ^2.4.12
  cloud_firestore: ^5.4.2
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_analytics: ^11.3.2
  firebase_core: ^3.5.0
  firebase_remote_config: ^5.1.2
  flutter_widget_from_html: ^0.15.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  provider: ^6.1.2
  reactive_forms: ^17.0.1
  reactive_date_time_picker: ^4.0.0
  reactive_raw_autocomplete: ^2.1.1
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/