// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:shared/models/birthplace.dart';
import 'package:shared/models/contact.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BirthplaceAdapter());
    registerAdapter(ContactAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BirthplaceAdapter());
    registerAdapter(ContactAdapter());
  }
}
