name: tax_code_flutter
description: "App for Italian Tax Code calculation."
publish_to: none # Remove this line if you wish to publish to pub.dev
version: 1.2.5+29

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  shared:
    path: ../shared

  animated_reorderable_list: ^1.1.1
  barcode_widget: ^2.0.4
  build_runner: ^2.4.13
  camera: ^0.11.0+2
  change_case: ^2.1.0
  cloud_firestore: ^5.4.4
  http: ^1.2.2
  firebase_analytics: ^11.3.3
  firebase_app_check: ^0.3.1+4
  firebase_auth: ^5.3.1
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.3
  firebase_remote_config: ^5.1.3
  firebase_ui_auth: ^1.16.0
  firebase_ui_localizations: ^1.13.0
  firebase_ui_oauth_google: ^1.4.0
  flutter_widget_from_html: ^0.15.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  internet_connection_checker_plus: ^2.5.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  material_symbols_icons: ^4.2788.0
  package_info_plus: ^8.0.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  reactive_forms: ^17.0.1
  reactive_date_time_picker: ^4.0.0
  reactive_raw_autocomplete: ^2.1.1
  screen_brightness: ^2.0.0+1
  share_plus: ^10.0.3
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/html/en/terms.html
    - assets/html/it/terms.html
    - assets/images/app_icon_512x512.png
    - assets/json/cities.json