name: tax_code_flutter
description: "App for Italian Tax Code calculation."
publish_to: none
version: 1.7.2+50

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Local module
  shared:
    path: ../shared

  # Core & Utilities
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  google_sign_in: ^6.3.0
  hive_ce_flutter: ^2.3.0
  image: ^4.5.3
  intl: ^0.20.0
  logger: ^2.8.0
  pdf: ^3.11.3
  provider: ^6.1.0
  shared_preferences: ^2.2.3
  uuid: ^4.6.0

  # UI & Widgets (Mobile specific)
  animated_reorderable_list: ^1.1.1
  barcode_widget: ^2.0.4
  flutter_svg: ^2.0.17
  google_fonts: ^6.3.0
  material_symbols_icons: ^4.2960.0
  material_ui: ^1.2.0
  reactive_date_time_picker: ^5.0.1
  reactive_forms: ^18.1.1
  reactive_raw_autocomplete: ^2.1.1

  # Platform Plugins (Mobile specific)
  camera: ^0.12.0
  package_info_plus: ^10.2.1
  permission_handler: ^12.0.1
  screen_brightness: ^2.1.0
  share_plus: ^13.3.0
  url_launcher: ^6.3.0

  # Firebase (Mobile specific UI/Services)
  cloud_functions: ^6.0.0
  firebase_app_check: ^0.4.0
  firebase_crashlytics: ^5.0.0
  firebase_remote_config: ^6.0.0
  firebase_storage: ^13.0.0
  in_app_review: ^2.0.11
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  camera_platform_interface: ^2.10.0
  firebase_auth_mocks: ^0.15.2
  firebase_core_platform_interface: ^8.1.1
  flutter_launcher_icons: ^0.14.4
  mocktail: ^1.0.4
  network_image_mock: ^2.1.1
  package_info_plus_platform_interface: ^4.1.0
  plugin_platform_interface: ^2.1.8
  remove_unused_localizations: ^1.1.2
  very_good_analysis: ^10.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/birthplaces.json
    - assets/images/google_logo.svg
    - assets/images/tax_code_icon.svg

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"
  adaptive_icon_monochrome: "assets/images/app_icon_monochrome.png"
