name: tax_code_flutter
description: "App for Italian Tax Code calculation."
publish_to: none
version: 1.4.1+41

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Local module
  shared:
    path: ../shared

  # Core & Utilities
  change_case: ^2.0.1
  hive_ce_flutter: ^2.3.0
  http: ^1.2.1
  intl: ^0.20.0
  logger: ^2.6.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

  # State Management
  provider: ^6.1.0

  # UI & Widgets (Mobile specific)
  animated_reorderable_list: ^1.1.1
  barcode_widget: ^2.0.4
  flutter_widget_from_html: ^0.17.0
  material_symbols_icons: ^4.2788.0
  reactive_date_time_picker: ^5.0.1
  reactive_forms: ^18.1.1
  reactive_raw_autocomplete: ^2.1.1

  # Platform Plugins (Mobile specific)
  camera: ^0.11.0+2
  screen_brightness: ^2.1.0
  share_plus: ^11.0.0
  package_info_plus: ^8.0.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0

  # Firebase (Mobile specific UI/Services)
  cloud_firestore: ^6.0.0
  firebase_analytics: ^12.0.0
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_remote_config: ^6.0.0
  firebase_ui_auth: ^3.0.0
  firebase_ui_localizations: ^2.0.0
  firebase_ui_oauth_google: ^2.0.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  google_sign_in: ^6.0.0
  cloud_functions: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  camera_platform_interface: ^2.10.0
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  package_info_plus_platform_interface: ^3.2.1
  plugin_platform_interface: ^2.1.8
  screen_brightness_platform_interface: ^2.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/html/en/terms.html
    - assets/html/it/terms.html
    - assets/images/app_icon_512x512.png
    - assets/json/cities.json
