name: shared
description: "Shared code for Tax Code app."
version: 1.4.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  # Core & Utilities
  equatable: ^2.0.5
  hive_ce: ^2.11.0
  hive_ce_flutter: ^2.3.0
  intl: ^0.20.0
  json_annotation: ^4.9.0
  logger: ^2.6.0
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

  # State Management
  provider: ^6.1.0

  # Firebase & Backend
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  google_sign_in: 6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.0
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.9.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

flutter:
  generate: true
