name: shared
description: "Shared code for Tax Code app."
version: 1.3.2
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

#================================================
# DEPENDENCIES
#================================================
dependencies:
  flutter:
    sdk: flutter

  # Core & Utilities
  intl: ^0.20.2 # Required for localization, pinned by Flutter SDK
  logger: ^2.6.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

  # UI & Widgets
  barcode_widget: ^2.0.4
  screen_brightness: ^2.1.5

  # State Management
  provider: ^6.1.2

  # Firebase & Backend
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.5.0
  firebase_remote_config: ^5.1.3

  # Code Generation
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0

#================================================
# DEV DEPENDENCIES
#================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.2
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4

#================================================
# FLUTTER CONFIGURATION
#================================================
flutter:
  generate: true
  uses-material-design: true
