name: shared
description: "Shared code for Tax Code app."
version: 1.2.1
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: any

  barcode_widget: ^2.0.4
  build_runner: ^2.4.13
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.5.0
  firebase_remote_config: ^5.1.3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  internet_connection_checker_plus: ^2.5.2
  json_annotation: ^4.9.0
  logger: ^2.4.0
  provider: ^6.1.2
  screen_brightness: ^2.0.0+1
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/html/en/terms.html
    - assets/html/it/terms.html
    - assets/images/app_icon_512x512.png
    - assets/json/cities.json
