name: tax_code_flutter_wear_os
description: "App for Italian Tax Code calculation, made for Wear OS."
publish_to: 'none'
version: 1.2.3+25

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Core dependencies
  intl: ^0.19.0
  shared:
    path: ../shared
  
  # UI & Functionality
  barcode_widget: ^2.0.4
  logger: ^2.0.2+1
  provider: ^6.1.1
  screen_brightness: ^2.0.0+1

  # Firebase
  firebase_auth: ^5.3.1
  firebase_core: ^3.5.0
  google_sign_in: ^6.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true