name: tax_code_flutter_wear_os
description: "App for Italian Tax Code calculation, made for Wear OS."
publish_to: "none"
version: 1.3.2+36

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Core & Utilities
  flutter_gen: ^5.10.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  shared:
    path: ../shared

  # UI & Functionality
  barcode_widget: ^2.0.4
  logger: ^2.6.0
  provider: ^6.1.1
  screen_brightness: ^2.1.5

  # Firebase & Backend
  cloud_firestore: ^5.4.4
  firebase_analytics: ^11.5.2
  firebase_app_check: ^0.3.2+9
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.9
  firebase_remote_config: ^5.4.7
  google_sign_in: 6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  google_sign_in_mocks: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
