name: tax_code_flutter_wear_os
description: "App for Italian Tax Code calculation, made for Wear OS."
publish_to: "none"
version: 1.6.0+45

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Local module
  shared:
    path: ../shared

  # Core & Utilities

  # State Management

  # UI & Functionality
  barcode_widget: ^2.0.4

  # Firebase & Backend
  firebase_app_check: ^0.4.0
  firebase_crashlytics: ^5.0.0
  firebase_remote_config: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8

flutter:
  generate: true
  uses-material-design: true
